name: thirty
description: Thirty.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Essentials
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  #Data management
  shared_preferences: ^0.5.6
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.2
  flutter_twitter_login: ^1.1.0
  provider: ^5.0.0

  #User interface
  page_transition: ^1.1.7+3
  intro_slider: ^2.3.3
  lottie: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - lib/assets/logos/googleLogo.png
      - lib/assets/logos/twitterLogo.png
      - lib/assets/images/welcomeBackgroundLightThemeImage.png
      - lib/assets/images/welcomeBackgroundDarkThemeImage.png
      - lib/assets/images/interfaceStandardsThemeSelectorMoonImage.png
      - lib/assets/images/interfaceStandardsThemeSelectorSunImage.png
      - lib/assets/animations/introCalendarAnimation.json
      - lib/assets/animations/introExerciseAnimation.json
      - lib/assets/animations/introMedalAnimation.json
      - lib/languages/en.json
      - lib/languages/es.json
      - lib/languages/fr.json