name: thirty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #Essentials
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  #Data management
  shared_preferences: ^0.5.6
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.14.0+5
  provider: ^3.2.0

  #User interface
  page_transition: ^1.1.7+3
  intro_slider: ^2.3.3
  lottie: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
      - lib/assets/welcomeBackgroundLightThemeImage.png
      - lib/assets/welcomeBackgroundDarkThemeImage.png
      - lib/assets/interfaceStandardsThemeSelectorMoonImage.png
      - lib/assets/interfaceStandardsThemeSelectorSunImage.png
      - lib/assets/introCalendarAnimation.json
      - lib/assets/introExerciseAnimation.json
      - lib/assets/introMedalAnimation.json
      - lib/languages/en.json
      - lib/languages/es.json
      - lib/languages/fr.json