name: thirty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.14.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
      - lib/assets/welcomeBackgroundLightThemeImage.png
      - lib/assets/welcomeBackgroundDarkThemeImage.png
      - lib/assets/interfaceStandardsThemeSelectorMoonImage.png
      - lib/assets/interfaceStandardsThemeSelectorSunImage.png
      - lib/assets/introCalendarAnimation.json
      - lib/assets/introExerciseAnimation.json
      - lib/assets/introMedalAnimation.json
      - lib/languages/en.json
      - lib/languages/es.json
      - lib/languages/fr.json