name: thirty
description: Thirty.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.14.0+5
  intl: ^0.16.1
  lottie: ^0.7.0+1
  intro_slider: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - lib/assets/welcomeBackgroundImage.png
      - lib/assets/introCalendarAnimation.json
      - lib/assets/introExerciseAnimation.json
      - lib/assets/introMedalAnimation.json
      - lib/languages/en.json
      - lib/languages/es.json
      - lib/languages/fr.json